SAMPLE_RUNS = [
    {
        "id": "sample-001",
        "url": "",
        "title": "GO Hanpass 웹 자동리포트_20260519_0910",
        "version": "5.20.4",
        "platform": "WEB_CHROME_SERVER",
        "status": "failed",
        "statusText": "실패",
        "pass": 72,
        "fail": 3,
        "na": 2,
        "total": 77,
        "resultText": "[96_full_menu_audit]\n- open_home: PASS\n- menu_payment: FAIL timeout\n- menu_travel: PASS\n[97_auto_click_payment]\n- payment_menu_charge: FAIL element detached",
        "failedItems": [
            {"scenario": "96_full_menu_audit", "name": "menu_payment", "status": "FAIL timeout"},
            {"scenario": "97_auto_click_payment", "name": "payment_menu_charge", "status": "FAIL element detached"},
        ],
        "snapshots": [],
        "createdAt": "2026-05-19T09:10:00+09:00",
        "lastEditedAt": "2026-05-19T09:14:00+09:00",
    },
    {
        "id": "sample-002",
        "url": "",
        "title": "GO Hanpass 웹 자동리포트_20260518_1519",
        "version": "5.20.4",
        "platform": "WEB_CHROME_SERVER",
        "status": "passed",
        "statusText": "성공",
        "pass": 74,
        "fail": 0,
        "na": 1,
        "total": 75,
        "resultText": "[01_login]\n- login_flow: PASS\n- web_signin_response_check: PASS",
        "failedItems": [],
        "snapshots": [],
        "createdAt": "2026-05-18T15:19:00+09:00",
        "lastEditedAt": "2026-05-18T15:22:00+09:00",
    },
    {
        "id": "sample-003",
        "url": "",
        "title": "GO Hanpass 웹 자동리포트_20260513_1521",
        "version": "5.19.0",
        "platform": "WEB_CHROME_SERVER",
        "status": "failed",
        "statusText": "실패",
        "pass": 61,
        "fail": 4,
        "na": 5,
        "total": 70,
        "resultText": "[96_full_menu_audit]\n- menu_payment: FAIL timeout\n- menu_remittance: FAIL overlay blocked",
        "failedItems": [
            {"scenario": "96_full_menu_audit", "name": "menu_payment", "status": "FAIL timeout"},
            {"scenario": "96_full_menu_audit", "name": "menu_remittance", "status": "FAIL overlay blocked"},
        ],
        "snapshots": [],
        "createdAt": "2026-05-13T15:21:00+09:00",
        "lastEditedAt": "2026-05-13T15:25:00+09:00",
    },
]
